[TestPSO]
VS = { Path = "Test.hlsl" , Entry = "VSMain", Macros = [] }
PS = { Path = "Test.hlsl", Entry = "PSMain", Macros = [] }
RVTFormats = ["R16G16B16A16_FLOAT"]

[TonemapCS]
CS = { Path = "Tonemap.hlsl" , Entry = "CSMain", Macros = [] }
